- id: go-lint
  name: lint golang files
  description: ensures golang code meets the configured lint criteria.
  entry: go-lint
  language: script
  pass_filenames: false
  stages: [pre-commit, pre-push, manual]
- id: go-mod-tidy
  name: go mod tidy
  description: ensure go mod is tidied before push
  entry: go-mod-tidy
  language: script
  stages: [pre-push, manual]
  pass_filenames: false